version : '3.1'

services:
  postgres:
    container_name: postgres_hapi
    image: postgres:9-alpine
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: unilim
      POSTGRES_PASSWORD: hapi
      POSTGRES_USER: hapi
